name: Security Scan

on:
  workflow_dispatch:
  push:
    branches:
      - bal-scan-e2e-test

jobs:
  call_workflow:
    name: Run Security Scan Workflow
    if: ${{ github.repository_owner == 'ballerina-platform' }}
    permissions:
      contents: read
      security-events: write
      actions: read
    uses: ballerina-platform/ballerina-library/.github/workflows/security-scan-template.yml@bal-scan-e2e
    secrets: inherit
